Excluding jcl-over-slf4j from sneaking into dependencies
If two slf4j versions (1.6 and 1.5) get into the project, it causes
version mismatches, and you get a dreaded error like:
java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log

Somehow the version bumps I've added to lucene, or other dependencies I've
added have caused slf4j to import jcl-over-slf4j (version 1.6). This fixes
that.